### PR TITLE
Fix bad merge

### LINKED ISSUE #101: Error when building `--with-ns`
Emacs-mac/master doesn't build anymore when configuring `--with-ns`:

```
  CC       emacs.o
emacs.c:3340:7: error: use of undeclared identifier 'autorelease'
 3340 |       autorelease = ns_alloc_autorelease_pool ();
      |       ^~~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by pkryger**
This is a cherry-picked 6ad349592f37ebacee1151dc67382df2bdf3ce54. Just to ensure branches are in sync.

Fixes: #101

### CODE REVIEW

**Comment by jdtsmith** [comment]
Thanks.
